pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                ./jenkins/build/mvn.sh mvn -B -Dskiptests clean package
                ./jenkins/build/build.sh                
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
